#
# Reforges
# by Auxilor
#

discover-recipes: true

gui:
  allow:
    material: anvil
    name: "&aReforge Item"
    lore:
      - '&7Reforges the above item, giving'
      - '&7it a random item modifier that'
      - '&7boosts its stats.'
      - ''
      - '&7Cost'
      - '&6\$%cost%'
      - ''
      - '&eClick to reforge!'
  allow-stone:
    material: anvil
    name: "&aReforge Item"
    lore:
      - '&7Reforges the above item with'
      - '&7a reforge stone, giving it'
      - '&7the %stone%&7 reforge to'
      - '&7boost its stats.'
      - ''
      - '&7Cost'
      - '&6\$%cost%'
      - ''
      - '&eClick to reforge!'
  no-item:
    material: anvil
    name: "&eReforge Item"
    lore:
      - '&7Place an item on the left to'
      - '&7reforge it! Reforging items adds a'
      - '&7random modifier to the item that'
      - '&7grants stat boosts'
  invalid-item:
    material: barrier
    name: "&cError!"
    lore:
      - '&7You cannot reforge this item!'

  sound:
    id: BLOCK_ANVIL_USE
    pitch: 1

  open-sound:
    id: BLOCK_ANVIL_PLACE
    pitch: 0.8

  stone-sound:
    id: ENTITY_ENDER_DRAGON_HURT
    pitch: 0.5

  insufficient-money-sound:
    id: ENTITY_VILLAGER_NO
    pitch: 0.8

reforge:
  cost: 7500

  cost-exponent: 1.15 # (Reforges done ^ cost exponent) * cost

  line-wrap: 32

  show-reforgable: true
  reforgable-suffix:
    - ""
    - "&8This item can be reforged!"

  display-in-lore: true

  stone:
    name: "%reforge%&f Reforge Stone"
    lore:
      - "&7Place on the right of the"
      - "&7reforge menu to apply the"
      - "%reforge%&7 reforge!"

targets:
  pickaxe:
    - wooden_pickaxe
    - stone_pickaxe
    - iron_pickaxe
    - golden_pickaxe
    - diamond_pickaxe
    - netherite_pickaxe
  melee:
    - wooden_axe
    - stone_axe
    - iron_axe
    - golden_axe
    - diamond_axe
    - netherite_axe
    - wooden_sword
    - stone_sword
    - iron_sword
    - golden_sword
    - diamond_sword
    - netherite_sword
  trident:
    - trident
  bow:
    - bow
    - crossbow
  armor:
    - turtle_helmet
    - leather_helmet
    - chainmail_helmet
    - iron_helmet
    - golden_helmet
    - diamond_helmet
    - netherite_helmet

    - leather_chestplate
    - chainmail_chestplate
    - iron_chestplate
    - golden_chestplate
    - diamond_chestplate
    - netherite_chestplate

    - leather_leggings
    - chainmail_leggings
    - iron_leggings
    - golden_leggings
    - diamond_leggings
    - netherite_leggings

    - leather_boots
    - chainmail_boots
    - iron_boots
    - golden_boots
    - diamond_boots
    - netherite_boots